<script type="text/javascript">


    var typeaheadTemplate = '<div class="afd-typeahead-container afd-form-control form-group admin__field">';
    typeaheadTemplate += '<div class="admin__field-label">';
    typeaheadTemplate += '<label>';
    typeaheadTemplate += '<span>Address Search</span>';
    typeaheadTemplate += '</label>';
    typeaheadTemplate += '</div>';
    typeaheadTemplate += '<div class="afd-typeahead-field admin__field-control">';
    typeaheadTemplate += '<div class="afd-typeahead-query">';
    typeaheadTemplate += '<input class="form-control" placeholder="Start typing your address" type="search" autocomplete="off" data-afd-control="typeahead" name="lion">';
    typeaheadTemplate += '</div>';
    typeaheadTemplate += '</div>';
    typeaheadTemplate += '</div>';

    afdOptions.postRender = {
        typeahead: {
            field: {
                selector: '[data-index="middlename"]',
                action: 'after',
                classes: 'admin__field',
                template: typeaheadTemplate
            },
            addressSearch: {
                selector: '[data-index="company"]',
                action: 'before'
            },
            searchAgain: {
                selector: '[data-index="company"]',
                action: 'before'
            },
            manualInput: {
                selector: '[data-index="company"]',
                action: 'before',
                template: '<div class="afd-manual-input-button">Manual Input</div>'
            },
            manualInputSearch: {
                selector: '[data-index="company"]',
                action: 'before'
            }
        },
        results: [
            ['[name="company"]', 'Organisation'],
            ['[name="street[0]"]', 'Property'],
            ['[name="street[1]"]', 'Street'],
            ['[name="street[2]"]', 'Locality'],
            ['[name="city"]', 'Town'],
            ['[name="region"]', 'PostalCounty']
        ]
    }
    afdOptions.typeahead.parentClass = 'admin__field';
    afdOptions.typeahead.containerOnlyContainsControl = true;
</script>

<script type="text/javascript">
    require(['jquery', 'afdPcePostRender'], function ($) {
        $(document).trigger('afd::initPostRender');
    });
</script>
