<?php if ($block->getConfig('typeahead/advanced/polyfill') == 1) { ?>
    <script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?flags=gated&features=Promise"></script>
<?php } ?>
<script>
    $ = window.jQuery;
    var afdOptions = {
        typeahead: {
            maxItems: '<?php echo $block->getConfig('typeahead/quantity/maxItems');?>',
            pushUp: true,
            afterHideTypeahead: '<?php echo $block->getConfig('typeahead/fields/afterHideTypeahead');?>' === '1',
            searchAgain: '<?php echo $block->getConfig('typeahead/fields/enableSearchAgainButton');?>' === '1',
            afterClearTypeahead: '<?php echo $block->getConfig('typeahead/fields/afterClearTypeahead');?>' === '1',
            beforeHideResults: '<?php echo $block->getConfig('typeahead/fields/beforeHideResults');?>' === '1',
            fewResultsManualInput: '<?php echo $block->getConfig('typeahead/quantity/enableFewItemsText');?>' === '1',
            fewResultsManualInputText: '<?php echo $block->escapeHtml($block->getConfig('typeahead/quantity/fewItemsText'));?>',
            notEmptyShowResults: true,
            parentClass: 'field',
            fieldSets: ['fieldset.street', 'fieldset [data-index="street"], .admin__field.field-street'],
            hideEmpties: '<?php echo $block->getConfig('typeahead/fields/hideEmpties');?>' === '1',
            manualInputButton: '<?php echo $block->getConfig('typeahead/fields/enableManualEntryButton');?>' === '1',
            containers: [],
            matchPositions: '<?php echo $block->getConfig('typeahead/fields/highlightMatches');?>' === '1',
            postcodeFirst: '<?php echo $block->getConfig('typeahead/fields/postcodeFirst');?>' === '1',
            showForCountries: '<?php echo $block->getConfig('typeahead/countries/typeaheadCountries');?>'.split(',')
        },
        country: {
            customCountryControl: '.modal-component [name="country_id"], .form-address-edit #country'
        },
        phone: {
            defaultDialingCode: '<?php echo $block->getConfig('phone/fields/dialingCode');?>'
        }
    };
    var hideStateCountries = '<?php echo $block->getConfig('typeahead/fields/hideRegion');?>'.split(',');
    <?php if($block->getConfig('general/account/method') == "id"){; ?>
        afdOptions.pceUrl = '<?php echo $block->getConfig('general/account/idPceUrl'); ?>';
        afdOptions.id = '<?php echo $block->getConfig('general/account/id'); ?>';
        afdOptions.token = '<?php echo $block->getConfig('general/account/token'); ?>';
    <?php } else { ?>
        afdOptions.pceUrl = '<?php echo $block->getConfig('general/account/serialPceUrl'); ?>';
        afdOptions.serial = '<?php echo $block->getConfig('general/account/serial'); ?>';
        afdOptions.password = '<?php echo $block->getConfig('general/account/password'); ?>';
    <?php } ?>

    // custom options that are needed in some parts of the application
    afdOptions.magentoOptions = {
        email: {
            emailEnabled: <?php echo $block->getConfig('email/enable/enable'); ?> === 1,
            accountChangeEmailEnabled: <?php echo $block->getConfig('email/forms/account'); ?> === 1,
            loggedOutCheckoutEnabled: <?php echo $block->getConfig('email/forms/checkout'); ?> === 1
        },
        phone: {
            phoneEnabled: <?php echo $block->getConfig('phone/enable/enable'); ?> === 1,
            loggedOutCheckoutEnabled: <?php echo $block->getConfig('phone/forms/checkout'); ?> === 1,
            invalidMessage: '<?php echo $block->getConfig("phone/fields/msg"); ?>'
        }

    }

</script>

<style>
    .afd-error {
        display: none;
    }


     .control.loading {
         position: relative
     }
    .field .control:before {
        border-color: rgba(0, 0, 0, 0.35);
    }
    .field .control.loading:before, .field .control.loading:after {
        transition: all 0s linear, opacity 0.2s ease;
        position: absolute;
        z-index: 3;
        content: "";
        top: 50%;
        right: 0.55em;
        margin-top: -0.675rem;
        width: 1.35rem;
        height: 1.35rem;
        box-sizing: border-box;
        border-radius: 500rem;
        border-style: solid;
        border-width: 0.1em;
    }

    .field .control._with-tooltip:before, .field .control._with-tooltip:after {
        right: 3.3em;
    }

    #shipping #customer-email-fieldset .control:before, #shipping #customer-email-fieldset .control:after {
        top: 25%;
    }

    .field .control:after {
        animation: button-spin 0.6s linear;
        animation-iteration-count: infinite;
        border-color: #fff transparent transparent;
        box-shadow: 0 0 0 1px transparent;
    }

    .afd-error {
        display: none;
        color: #e02b27;
        font-size: 1.2rem;
        margin-top: 7px;

    }

    .afd-invalid + .afd-error {
        display: block;
    }

    input.afd-invalid {
        border-color: #ed8380;
    }

    .afd-loading {
        position: relative;
    }

    .afd-loading:before, .afd-loading:after {
        transition: all 0s linear, opacity 0.2s ease;
        position: absolute;
        z-index: 3;
        content: "";
        top: 1.2em !important;
        right: 1em;
        margin-top: -0.675rem;
        width: 1.35rem;
        height: 1.35rem;
        box-sizing: border-box;
        border-radius: 500rem;
        border-style: solid;
        border-width: 0.1em;
    }

    .afd-loading:before {
        border-color: rgba(0, 0, 0, 0.35);
    }

    .afd-loading:after {
        animation: button-spin 0.6s linear;
        animation-iteration-count: infinite;
        border-color: #fff transparent transparent;
        box-shadow: 0 0 0 1px transparent;
    }

    @keyframes button-spin {
        from {
            transform: rotate(0deg);
        }
        to {
            transform: rotate(360deg);
        }
    }


</style>