<?php // not ok needs fixing ?>

<script type="text/javascript">

    require(['jquery', 'afdPce', 'domReady!app/Afd/Pce/view/base/templates/afd'], function ($) {

        
        $(document).on('afd:phoneValidationStared', function(e, el){
            var $el = $(el);
            $el.parent().addClass('afd-loading');
        });
        $(document).on('afd:phoneValidationUpdated', function(e, el){
            var $el = $(el);
            $el.parent().removeClass('afd-loading');
        });

    });


</script>
